namespace ImageRenamr.Core.Models;

/// <summary>
/// Represents the result of a batch image renaming operation,
/// including counts of processed files and the list of
/// output file paths.
/// </summary>
/// <remarks>
/// Use this record to inspect the outcome of an image renaming process,
/// including which files were affected and which were skipped.
/// The counts and file list can be used for reporting or further processing.
/// </remarks>
/// <param name="TotalFiles">The total number of image files that
/// were considered for renaming during the operation.</param>
/// <param name="CopiedFiles">The number of image files that were
/// successfully copied or renamed.</param>
/// <param name="SkippedFiles">The number of image files that were
/// skipped and not renamed or copied.</param>
/// <param name="OutputFiles">A read-only list containing the full paths
/// of the output files generated by the operation.</param>
public sealed record RenameImagesResult(
    int TotalFiles,
    int CopiedFiles,
    int SkippedFiles,
    IReadOnlyList<string> OutputFiles);
