<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <AssemblyName>ImageRenamr.App</AssemblyName>
        <RootNamespace>ImageRenamr.App</RootNamespace>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <NeutralLanguage>en</NeutralLanguage>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Semi.Avalonia" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ImageRenamr.Core\ImageRenamr.Core.csproj" />
    </ItemGroup>
</Project>
